//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderInfo
    {
        public int OrderID { get; set; }
        public Nullable<int> opid { get; set; }
        public int qty { get; set; }
        public Nullable<int> payment { get; set; }
        public Nullable<int> status1 { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
